CREATE DATABASE PruebaSeedCode
USE PruebaSeedCode

CREATE TABLE roles(
Id INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(50) NOT NULL UNIQUE
);

--Usuarios
CREATE TABLE users(
Id INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL UNIQUE,
Passwordd VARCHAR(255) NOT NULL, 
role_id INT NOT NULL, 
FOREIGN KEY (role_id) REFERENCES roles(id)
);